# Generated by Django 4.2.10 on 2024-02-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('director', models.TextField(max_length=100)),
                ('completed', models.BooleanField(default=True)),
            ],
        ),
    ]
